### ISSUE TITLE
Additional metadata in container?

### ISSUE THREAD

**Issue by gkelly** [ragona/quorum#1]
Is it worth adding additional metadata in the output container? With the current construction I think you can successfully mix and match shares from different quorums to accidentally produce novel 'secrets'. Even just putting a shared random 32bit value in the container as a quorum tag and checking at `decrypt`-time that they're all the same would prevent this.

I tested this locally and because you're using authenticated encryption you're not getting random spew on the output, but it's a fairly unsatisfying: `Error: Failed to decrypt ciphertext: ring::error::Unspecified`

https://github.com/ragona/quorum/blob/618aad2fefa5911c04120dbcb7032926722e3e44/src/quorum.rs#L25

**Comment by ragona** [comment]
Oo this would actually solve some thinking I’ve been doing on a `rekey` command I have locally. You’re totally right, if you combine unlike shares it will fail at the decryption, not the secret recovery. Lemme think about that, I recall some similar issues from the first implementation of a similar tool we worked on.

**Comment by ragona** [comment]
Updated. After this diff (https://github.com/ragona/quorum/commit/575f914beb15afe59efeb7182e822baa024dc13a) each share has a 32-byte `quorum_share_id`, and mismatched shares will now produce this error:
```
➜  quorum decrypt a/quorum_share_0.priv b/quorum_share_0.priv a/quorum_share_1.priv
Error: Failed to recover secret: Shares are from different groups
```
