### ISSUE TITLE
Ergonomics of ChaCha20-Poly1305

### ISSUE THREAD

**Issue by gkelly** [ragona/quorum#2]
One thing that strikes me as potentially useful for a tool like this is the ability to encrypt a value to the quorum without having to assemble the quorum, which potentially increases the exposure of the key material. If you generated instead an ed25519 private key and Shamir split it and also output the public key then you could encrypt to the quorum without needing the key assembled.

I can also see the argument that needing quorum to _create_ sealed values is a feature.

https://github.com/ragona/quorum/blob/618aad2fefa5911c04120dbcb7032926722e3e44/src/encrypt.rs#L66

This is an unhelpful issue, it's just philosophizing around decision decisions you've already made. Sorry!

**Comment by ragona** [comment]
Oh that is a good thought. I like the idea of being able to encrypt without a quorum. We could potentially embed the pubkey into each share to allow a single user share to encrypt a message, that’d be very useful and would keep the share from coming together as often.

**Comment by ragona** [comment]
Updated, thank you for the excellent suggestion! I removed `ring` in favor of `ecies`, which now allows the `encrypt` command to simply take a public key rather than a quorum of private shares: https://github.com/ragona/quorum/commit/ccf294e302e407906a56225a8f26a4575f019f70
